version: '3.8'

services:
  # --- 1. API GATEWAY MANAGER (Seu Serviço Principal) ---
  gateway:
    build: .
    container_name: api-gateway-manager
    # Mapeamento: Host 8000 -> Container 8000
    ports:
      - "8000:8000"
    restart: always
    environment:
      # Conexão com MongoDB no Docker
      MONGO_URI: mongodb://mongo-db:27017/api-gateway-db
      JWT_SECRET: PieGoCAmiSa10
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password123
      # CORREÇÃO: Variável que seu app.js usa, mapeada para o Host
      PORT_CHECK_HOST: host.docker.internal 
    depends_on:
      - mongo-db
      
  # --- 2. MONGODB DATABASE ---
  mongo-db:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# Definição do volume para persistência de dados
volumes:
  mongo-data:
